# Generated by Django 4.2.23 on 2025-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_quantity_alter_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_method',
            field=models.TextField(blank=True, help_text='Describe the step-by-step cooking method or instructions.'),
        ),
    ]
